### ISSUE TITLE
Widget shows only camera button and white screen

### ISSUE THREAD

**Issue by yamcomnet** [kivy-garden/xcamera#42]
Widget shows camera button and white screen.
When i press camera button my debug says following:

04-23 10:41:02.293 20776 20951 I python  : [WARNING] [Base        ] Unknown <android> provider
04-23 10:41:02.294 20776 20951 I python  : [INFO   ] [Base        ] Start application main loop
04-23 10:43:11.955 20776 20951 I python  : [INFO   ] [xcamera     ] starting autofocus...
04-23 10:43:11.960 20776 20951 I python  : [INFO   ] [Error when calling autofocus] JVM exception occurred: autoFocus failed java.lang.RuntimeException

on_camera_ready method is not fired. 
Phone OS MIUI V12.012.0.QCSEUXM

Is this because platform is not supported, any way to investigate?

Just tried plyer camera. Looks like this is just a platform issue:

04-23 11:07:34.286 22391 22563 I python  :  Traceback (most recent call last):
04-23 11:07:34.287 22391 22563 I python  :    File "/home/to/KivyMD/demos/bafinfeh/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/armeabi-v7a/plyer/utils.py", line 93, in _ensure_obj
04-23 11:07:34.287 22391 22563 I python  :    File "/home/to/KivyMD/demos/bafinfeh/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/armeabi-v7a/plyer/platforms/android/camera.py", line 9, in <module>
04-23 11:07:34.288 22391 22563 I python  :    File "/home/to/KivyMD/demos/bafinfeh/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/armeabi-v7a/jnius/reflect.py", line 229, in autoclass
04-23 11:07:34.288 22391 22563 I python  :    File "jnius/jnius_export_func.pxi", line 26, in jnius.jnius.find_javaclass
04-23 11:07:34.289 22391 22563 I python  :    File "jnius/jnius_utils.pxi", line 91, in jnius.jnius.check_exception
04-23 11:07:34.289 22391 22563 I python  :  jnius.jnius.JavaException: JVM exception occurred: Didn't find class "org.renpy.android.PythonActivity" on path: DexPathList[[zip file "/data/app/com.bafinfeh.logger.myapp-bwsgvvmgMmynmg3i2FETeg==/base.apk"],nativeLibraryDirectories=[/data/app/com.bafinfeh.logger.myapp-bwsgvvmgMmynmg3i2FETeg==/lib/arm, /data/app/com.bafinfeh.logger.myapp-bwsgvvmgMmynmg3i2FETeg==/base.apk!/lib/armeabi-v7a, /system/lib, /product/lib]] java.lang.ClassNotFoundException

**Comment by ChristopherYoon89** [comment]
Just in case you haven't solved it yet or someone else has the same problem:

You need to set the play parameter as True like:

`self.xcamera.play = True`

I had the same problem, but could finally resolve it.

**Comment by nesergen** [comment]
Kivy 2.2.1 , Android 7.0 , Huawei MediaPad T3
The same problem. White screen and error on focus.
`06-15 21:40:24.329 21842 21987 I python  : [INFO   ] [xcamera     ] starting autofocus...
06-15 21:40:24.330   576  9305 I Camera2Client: autoFocus: Camera 0
06-15 21:40:24.330   576  9305 E Camera2Client: autoFocus: Camera 0: Call autoFocus when preview is inactive (state = 1).
06-15 21:40:24.332 21842 21987 I python  : [INFO   ] [Error when calling autofocus] JVM exception occurred: autoFocus failed java.lang.RuntimeException`
