### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by rlimaeco** [kivy-garden/xcamera#7]
This happens when I run in my desktop, apk and kivy launcher via deploy.sh
And this  code line: >>   28:    resolution: 640, 480 # 1920, 1080

is related to the last commit, maybe is just happening with me .

```
`11-21 18:25:29.689  1882  1910 I python  :  Traceback (most recent call last):
11-21 18:25:29.690  1882  1910 I python  :    File "main.py", line 38, in <module>
11-21 18:25:29.691  1882  1910 I python  :      CameraApp().run()
11-21 18:25:29.692  1882  1910 I python  :    File "/home/tito/code/python-for-android-upstream/build/python-install/lib/python2.7/site-packages/kivy/app.py", line 802, in run
11-21 18:25:29.693  1882  1910 I python  :    File "main.py", line 32, in build
11-21 18:25:29.694  1882  1910 I python  :      return Builder.load_string(kv)
11-21 18:25:29.696  1882  1910 I python  :    File "/home/tito/code/python-for-android-upstream/build/python-install/lib/python2.7/site-packages/kivy/lang.py", line 1921, in load_string
11-21 18:25:29.699  1882  1910 I python  :    File "/home/tito/code/python-for-android-upstream/build/python-install/lib/python2.7/site-packages/kivy/lang.py", line 2084, in _apply_rule
11-21 18:25:29.702  1882  1910 I python  :    File "/home/tito/code/python-for-android-upstream/build/python-install/lib/python2.7/site-packages/kivy/lang.py", line 1970, in apply
11-21 18:25:29.706  1882  1910 I python  :    File "/home/tito/code/python-for-android-upstream/build/python-install/lib/python2.7/site-packages/kivy/lang.py", line 2130, in _apply_rule
11-21 18:25:29.711  1882  1910 I python  :  kivy.lang.BuilderException: Parser: File "<inline>", line 28:
11-21 18:25:29.712  1882  1910 I python  :  ...
11-21 18:25:29.714  1882  1910 I python  :       26:
11-21 18:25:29.716  1882  1910 I python  :       27:    id: camera
11-21 18:25:29.718  1882  1910 I python  :  >>   28:    resolution: 640, 480 # 1920, 1080
11-21 18:25:29.720  1882  1910 I python  :       29:    allow_stretch: True
11-21 18:25:29.722  1882  1910 I python  :       30:
11-21 18:25:29.724  1882  1910 I python  :  ...
11-21 18:25:29.726  1882  1910 I python  :  JavaException: JVM exception occurred: Fail to connect to camera service
11-21 18:25:29.728  1882  1910 I python  :    File "/home/tito/code/python-for-android-upstream/build/python-install/lib/python2.7/site-packages/kivy/lang.py", line 2123, in _apply_rule
11-21 18:25:29.730  1882  1910 I python  :    File "kivy/weakproxy.pyx", line 22, in kivy.weakproxy.WeakProxy.__setattr__ (kivy/weakproxy.c:1235)
11-21 18:25:29.732  1882  1910 I python  :    File "kivy/properties.pyx", line 408, in kivy.properties.Property.__set__ (kivy/properties.c:5114)
11-21 18:25:29.734  1882  1910 I python  :    File "kivy/properties.pyx", line 733, in kivy.properties.ListProperty.set (kivy/properties.c:11127)
11-21 18:25:29.736  1882  1910 I python  :    File "kivy/properties.pyx", line 446, in kivy.properties.Property.set (kivy/properties.c:5876)
11-21 18:25:29.738  1882  1910 I python  :    File "kivy/properties.pyx", line 501, in kivy.properties.Property.dispatch (kivy/properties.c:6557)
11-21 18:25:29.739  1882  1910 I python  :    File "kivy/_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy/_event.c:13497)
11-21 18:25:29.740  1882  1910 I python  :    File "kivy/_event.pyx", line 1130, in kivy._event.EventObservers._dispatch (kivy/_event.c:12696)
11-21 18:25:29.741  1882  1910 I python  :    File "/home/tito/code/python-for-android-upstream/build/python-install/lib/python2.7/site-packages/kivy/uix/camera.py", line 103, in _on_index
11-21 18:25:29.742  1882  1910 I python  :    File "/home/tito/code/python-for-android-upstream/build/python-install/lib/python2.7/site-packages/kivy/core/camera/camera_android.py", line 40, in __init__
11-21 18:25:29.743  1882  1910 I python  :    File "/home/tito/code/python-for-android-upstream/build/python-install/lib/python2.7/site-packages/kivy/core/camera/__init__.py", line 70, in __init__
11-21 18:25:29.743  1882  1910 I python  :    File "/home/tito/code/python-for-android-upstream/build/python-install/lib/python2.7/site-packages/kivy/core/camera/camera_android.py", line 47, in init_camera
11-21 18:25:29.744  1882  1910 I python  :    File "jnius/jnius_export_class.pxi", line 906, in jnius.jnius.JavaMultipleMethod.__call__ (jnius/jnius.c:27875)
11-21 18:25:29.745  1882  1910 I python  :    File "jnius/jnius_export_class.pxi", line 637, in jnius.jnius.JavaMethod.__call__ (jnius/jnius.c:24246)
11-21 18:25:29.746  1882  1910 I python  :    File "jnius/jnius_export_class.pxi", line 803, in jnius.jnius.JavaMethod.call_staticmethod (jnius/jnius.c:26271)
11-21 18:25:29.746  1882  1910 I python  :    File "jnius/jnius_utils.pxi", line 93, in jnius.jnius.check_exception (jnius/jnius.c:3870)
11-21 18:25:29.747  1882  1910 I python  :  
11-21 18:25:29.811  1882  1910 I python  : Python for android ended.
````

Regards

**Comment by AndreMiras** [comment]
fixed via https://github.com/kivy-garden/xcamera/issues/5 and https://github.com/kivy-garden/xcamera/commit/a8292d984b43bc4fdc03e795c7ab0da046218c3a
